### ISSUE TITLE
package directory structure...

### ISSUE THREAD

**Issue by steviesama** [tj/go-dropbox#21]
...is non-existent. I had to create it myself.

**Comment by tj** [comment]
?

**Comment by tj** [comment]
Feel free to re-open and clarify what the issue is, this just looks like random complaining of something? I'm not even sure what haha..

**Comment by steviesama** [comment]
Ah, sorry. I was in a hurry doing something else after I'd fixed it and just continued typing the rest starting from the issue title. The directory structure for the package items don't have directories for the package names you set up for some of the files. So when you go build it breaks. I had to go make directories with the names of the packages you set up in the source files, and then copy the files to those directories before it would work.
