### ISSUE TITLE
listing top level folders/files

### ISSUE THREAD

**Issue by mickelsonm** [tj/go-dropbox#8]
Hey @tj , first of all this looks great and thank you for creating this.

So I have a folder/file structure like this:

```
/
/school/
/work/
/pictures/
/resume.pdf
```

I try using a path of "/" in my [test program](http://play.golang.org/p/30POYng9MU) and I get a `path/malformed_path/` response back. But if I use a folder a level down (ex: "/school") it works just fine.

So the question is how do I list the top-level stuff? I just checked out the Dropbox API itself and I didn't see anything. Any thoughts about how to handle this? Thanks!

**Comment by tj** [comment]
Hmm I've just been testing with an app dir and those sorts of requests seem fine, not sure off-hand, I'll dig into that once I get a test account going.

**Comment by tj** [comment]
Forgot that they make you use "" for root, definitely a little awkward

**Comment by mickelsonm** [comment]
Yeah that is a little awkward. Anyways, thanks again!
